workspace '../CFFoundation.xcworkspace'
platform :ios, '9.0'

target 'CFFoundation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CFFoundation
  pod 'CocoaLumberjack', '~> 3.5.3'

  target 'CFFoundationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
